-- 01_db.sql
-- Create repositories table
CREATE TABLE IF NOT EXISTS repositories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    github_id BIGINT UNIQUE NOT NULL,
    owner TEXT NOT NULL,
    name TEXT NOT NULL,
    description TEXT,
    language TEXT,
    stars INTEGER,
    forks INTEGER,
    issues INTEGER,
    score FLOAT DEFAULT 0,
    created_at TIMESTAMPTZ,
    updated_at TIMESTAMPTZ,
    last_scanned_at TIMESTAMPTZ
);

-- Create metrics history table
CREATE TABLE IF NOT EXISTS metrics_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    repo_id BIGINT REFERENCES repositories(id),
    captured_at TIMESTAMPTZ DEFAULT NOW(),
    stars INTEGER,
    forks INTEGER
);

-- Create index for score
CREATE INDEX IF NOT EXISTS idx_repositories_score ON repositories(score DESC);

-- Create index for language
CREATE INDEX IF NOT EXISTS idx_repositories_language ON repositories(language);
