-- 01_db.sql
-- Create repositories table
CREATE TABLE IF NOT EXISTS repositories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    github_id BIGINT UNIQUE NOT NULL,
    owner TEXT NOT NULL,
    name TEXT NOT NULL,
    description TEXT,
    language TEXT,
    stars INTEGER,
    forks INTEGER,
    issues INTEGER,
    score FLOAT DEFAULT 0,
    created_at TIMESTAMPTZ,
    updated_at TIMESTAMPTZ,
    last_scanned_at TIMESTAMPTZ,
    -- Creator quality metrics
    owner_followers INTEGER DEFAULT 0,
    owner_repo_count INTEGER DEFAULT 0,
    -- Trending indicator
    velocity_badge TEXT
);

-- Create metrics history table
CREATE TABLE IF NOT EXISTS metrics_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    repo_id BIGINT REFERENCES repositories(id),
    captured_at TIMESTAMPTZ DEFAULT NOW(),
    stars INTEGER,
    forks INTEGER
);

-- Create index for score
CREATE INDEX IF NOT EXISTS idx_repositories_score ON repositories(score DESC);

-- Create index for language
CREATE INDEX IF NOT EXISTS idx_repositories_language ON repositories(language);

-- Create index for created_at (for date sorting)
CREATE INDEX IF NOT EXISTS idx_repositories_created_at ON repositories(created_at DESC);

-- Create index for foreign key in metrics_history (improves JOIN performance)
CREATE INDEX IF NOT EXISTS idx_metrics_history_repo_id ON metrics_history(repo_id);

-- Archive table for snapshots before each collector run (keeps history, no leftover in main list)
CREATE TABLE IF NOT EXISTS repositories_archive (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    archived_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    github_id BIGINT NOT NULL,
    owner TEXT NOT NULL,
    name TEXT NOT NULL,
    description TEXT,
    language TEXT,
    stars INTEGER,
    forks INTEGER,
    issues INTEGER,
    score FLOAT DEFAULT 0,
    created_at TIMESTAMPTZ,
    updated_at TIMESTAMPTZ,
    last_scanned_at TIMESTAMPTZ,
    owner_followers INTEGER DEFAULT 0,
    owner_repo_count INTEGER DEFAULT 0,
    velocity_badge TEXT
);

CREATE INDEX IF NOT EXISTS idx_repositories_archive_archived_at ON repositories_archive(archived_at DESC);

-- Cap existing scores to 100 (no-op on fresh DB)
UPDATE repositories SET score = 100 WHERE score > 100;
