-- 01_schema.sql — tables, indexes, and RLS (canonical fresh install)

CREATE TABLE IF NOT EXISTS repositories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    github_id BIGINT UNIQUE NOT NULL,
    owner TEXT NOT NULL,
    name TEXT NOT NULL,
    description TEXT,
    language TEXT,
    stars INTEGER,
    forks INTEGER,
    issues INTEGER,
    score FLOAT DEFAULT 0,
    created_at TIMESTAMPTZ,
    updated_at TIMESTAMPTZ,
    last_scanned_at TIMESTAMPTZ,
    owner_followers INTEGER DEFAULT 0,
    owner_repo_count INTEGER DEFAULT 0,
    velocity_badge TEXT
);

CREATE TABLE IF NOT EXISTS metrics_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    repo_id BIGINT REFERENCES repositories(id),
    captured_at TIMESTAMPTZ DEFAULT NOW(),
    stars INTEGER,
    forks INTEGER
);

CREATE TABLE IF NOT EXISTS repositories_archive (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    archived_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    github_id BIGINT NOT NULL,
    owner TEXT NOT NULL,
    name TEXT NOT NULL,
    description TEXT,
    language TEXT,
    stars INTEGER,
    forks INTEGER,
    issues INTEGER,
    score FLOAT DEFAULT 0,
    created_at TIMESTAMPTZ,
    updated_at TIMESTAMPTZ,
    last_scanned_at TIMESTAMPTZ,
    owner_followers INTEGER DEFAULT 0,
    owner_repo_count INTEGER DEFAULT 0,
    velocity_badge TEXT
);

-- Global curation flags keyed by stable github_id (survives archive-and-clear).
CREATE TABLE IF NOT EXISTS repo_flags (
    github_id BIGINT NOT NULL,
    flag TEXT NOT NULL CHECK (flag IN ('saved', 'hidden')),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    PRIMARY KEY (github_id, flag)
);

-- Indexes
CREATE INDEX IF NOT EXISTS idx_repositories_score ON repositories(score DESC);
CREATE INDEX IF NOT EXISTS idx_repositories_language ON repositories(language);
CREATE INDEX IF NOT EXISTS idx_repositories_created_at ON repositories(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_metrics_history_repo_id ON metrics_history(repo_id);
CREATE INDEX IF NOT EXISTS idx_repositories_archive_archived_at ON repositories_archive(archived_at DESC);
CREATE INDEX IF NOT EXISTS idx_repositories_archive_github_archived ON repositories_archive (github_id, archived_at);
CREATE INDEX IF NOT EXISTS idx_repo_flags_flag ON repo_flags (flag);

-- Row Level Security
ALTER TABLE repositories ENABLE ROW LEVEL SECURITY;
ALTER TABLE metrics_history ENABLE ROW LEVEL SECURITY;
ALTER TABLE repositories_archive ENABLE ROW LEVEL SECURITY;
ALTER TABLE repo_flags ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public read access on repositories"
    ON repositories FOR SELECT TO public USING (true);

CREATE POLICY "Allow authenticated insert on repositories"
    ON repositories FOR INSERT TO authenticated
    WITH CHECK ((select auth.uid()) IS NOT NULL);

CREATE POLICY "Allow authenticated update on repositories"
    ON repositories FOR UPDATE TO authenticated
    USING ((select auth.uid()) IS NOT NULL)
    WITH CHECK ((select auth.uid()) IS NOT NULL);

CREATE POLICY "Allow authenticated delete on repositories"
    ON repositories FOR DELETE TO authenticated
    USING ((select auth.uid()) IS NOT NULL);

CREATE POLICY "Allow public read access on metrics_history"
    ON metrics_history FOR SELECT TO public USING (true);

CREATE POLICY "Allow authenticated insert on metrics_history"
    ON metrics_history FOR INSERT TO authenticated
    WITH CHECK ((select auth.uid()) IS NOT NULL);

CREATE POLICY "Allow authenticated update on metrics_history"
    ON metrics_history FOR UPDATE TO authenticated
    USING ((select auth.uid()) IS NOT NULL)
    WITH CHECK ((select auth.uid()) IS NOT NULL);

CREATE POLICY "Allow authenticated delete on metrics_history"
    ON metrics_history FOR DELETE TO authenticated
    USING ((select auth.uid()) IS NOT NULL);

CREATE POLICY "Allow public read access on repositories_archive"
    ON repositories_archive FOR SELECT TO public USING (true);

CREATE POLICY "Allow authenticated insert on repositories_archive"
    ON repositories_archive FOR INSERT TO authenticated
    WITH CHECK ((select auth.uid()) IS NOT NULL);

-- Personal single-user tool: flags are global and writable by anon.
CREATE POLICY "Allow public read access on repo_flags"
    ON repo_flags FOR SELECT TO public USING (true);

CREATE POLICY "Allow public insert on repo_flags"
    ON repo_flags FOR INSERT TO public
    WITH CHECK (github_id IS NOT NULL AND flag IN ('saved', 'hidden'));

CREATE POLICY "Allow public delete on repo_flags"
    ON repo_flags FOR DELETE TO public
    USING (github_id IS NOT NULL AND flag IN ('saved', 'hidden'));
