package storage

import (
	"database/sql"
	"fmt"
	"time"

	"github.com/babacar/gemhunter/internal/models"
	_ "github.com/jackc/pgx/v5/stdlib"
)

type Store struct {
	db *sql.DB
}

func NewStore(connString string) (*Store, error) {
	db, err := sql.Open("pgx", connString)
	if err != nil {
		return nil, fmt.Errorf("failed to open database: %w", err)
	}
	if err := db.Ping(); err != nil {
		return nil, fmt.Errorf("failed to ping database: %w", err)
	}
	return &Store{db: db}, nil
}

func (s *Store) Init() error {
	query := `
	CREATE TABLE IF NOT EXISTS repositories (
		id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
		github_id BIGINT UNIQUE NOT NULL,
		owner TEXT NOT NULL,
		name TEXT NOT NULL,
		description TEXT,
		language TEXT,
		stars INTEGER,
		forks INTEGER,
		issues INTEGER,
		score FLOAT DEFAULT 0,
		created_at TIMESTAMPTZ,
		updated_at TIMESTAMPTZ,
		last_scanned_at TIMESTAMPTZ
	);
	CREATE TABLE IF NOT EXISTS metrics_history (
		id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
		repo_id BIGINT REFERENCES repositories(id),
		captured_at TIMESTAMPTZ DEFAULT NOW(),
		stars INTEGER,
		forks INTEGER
	);
	CREATE INDEX IF NOT EXISTS idx_repositories_score ON repositories(score DESC);
	`
	_, err := s.db.Exec(query)
	if err != nil {
		return fmt.Errorf("failed to init schema: %w", err)
	}
	return nil
}

func (s *Store) SaveRepo(r *models.Repository) error {
	query := `
	INSERT INTO repositories (github_id, owner, name, description, language, stars, forks, issues, score, created_at, updated_at, last_scanned_at, owner_followers, owner_repo_count, velocity_badge)
	VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15)
	ON CONFLICT(github_id) DO UPDATE SET
		stars = excluded.stars,
		forks = excluded.forks,
		issues = excluded.issues,
		score = excluded.score,
		updated_at = excluded.updated_at,
		last_scanned_at = excluded.last_scanned_at,
		owner_followers = excluded.owner_followers,
		owner_repo_count = excluded.owner_repo_count,
		velocity_badge = excluded.velocity_badge
	RETURNING id;
	`
	var repoID int64
	err := s.db.QueryRow(query, 
		r.GithubID, r.Owner, r.Name, r.Description, r.Language, 
		r.Stars, r.Forks, r.Issues, r.Score, r.CreatedAt, r.UpdatedAt, r.LastScannedAt,
		r.OwnerFollowers, r.OwnerRepoCount, r.VelocityBadge,
	).Scan(&repoID)
	
	if err != nil {
		return fmt.Errorf("failed to save repo: %w", err)
	}

	r.ID = repoID

	_, err = s.db.Exec(`INSERT INTO metrics_history (repo_id, stars, forks) VALUES ($1, $2, $3)`, repoID, r.Stars, r.Forks)
	return err
}

func (s *Store) ListRepos() ([]models.Repository, error) {
	rows, err := s.db.Query(`SELECT id, github_id, owner, name, description, language, stars, forks, issues, created_at, updated_at, last_scanned_at FROM repositories ORDER BY stars DESC LIMIT 100`)
	if err != nil {
		return nil, fmt.Errorf("query failed: %w", err)
	}
	defer rows.Close()

	var repos []models.Repository
	for rows.Next() {
		var r models.Repository
		if err := rows.Scan(
			&r.ID, &r.GithubID, &r.Owner, &r.Name, &r.Description, &r.Language,
			&r.Stars, &r.Forks, &r.Issues, &r.CreatedAt, &r.UpdatedAt, &r.LastScannedAt,
		); err != nil {
			return nil, err
		}
		repos = append(repos, r)
	}
	return repos, nil
}

func (s *Store) Close() error {
	return s.db.Close()
}

// PruneOldRepos deletes repositories not scanned in the last `days` days.
// Returns the number of repos deleted.
func (s *Store) PruneOldRepos(days int) (int64, error) {
	// First delete metrics_history for repos we're about to remove (FK constraint)
	_, err := s.db.Exec(`
		DELETE FROM metrics_history
		WHERE repo_id IN (
			SELECT id FROM repositories
			WHERE last_scanned_at < NOW() - make_interval(days => $1)
			   OR (last_scanned_at IS NULL AND updated_at < NOW() - make_interval(days => $1))
			   OR (last_scanned_at IS NULL AND updated_at IS NULL AND created_at < NOW() - make_interval(days => $1))
		)
	`, days)
	if err != nil {
		return 0, fmt.Errorf("failed to prune metrics for old repos: %w", err)
	}

	result, err := s.db.Exec(`
		DELETE FROM repositories
		WHERE last_scanned_at < NOW() - make_interval(days => $1)
		   OR (last_scanned_at IS NULL AND updated_at < NOW() - make_interval(days => $1))
		   OR (last_scanned_at IS NULL AND updated_at IS NULL AND created_at < NOW() - make_interval(days => $1))
	`, days)
	if err != nil {
		return 0, fmt.Errorf("failed to prune repos: %w", err)
	}
	n, _ := result.RowsAffected()
	return n, nil
}

// PruneOrphanedMetricsHistory removes metrics_history for repos that no longer exist.
func (s *Store) PruneOrphanedMetricsHistory() (int64, error) {
	result, err := s.db.Exec(`
		DELETE FROM metrics_history mh
		WHERE NOT EXISTS (SELECT 1 FROM repositories r WHERE r.id = mh.repo_id)
	`)
	if err != nil {
		return 0, fmt.Errorf("failed to prune orphaned metrics: %w", err)
	}
	n, _ := result.RowsAffected()
	return n, nil
}

// PruneOldMetricsHistory keeps only the last N days of metrics per repo.
// Older rows are deleted to prevent unbounded growth.
func (s *Store) PruneOldMetricsHistory(days int) (int64, error) {
	result, err := s.db.Exec(`
		DELETE FROM metrics_history
		WHERE captured_at < NOW() - make_interval(days => $1)
	`, days)
	if err != nil {
		return 0, fmt.Errorf("failed to prune old metrics: %w", err)
	}
	n, _ := result.RowsAffected()
	return n, nil
}

// GetLastScannedAt returns the most recent last_scanned_at across all repos.
func (s *Store) GetLastScannedAt() (*time.Time, error) {
	var t time.Time
	err := s.db.QueryRow(`SELECT MAX(last_scanned_at) FROM repositories`).Scan(&t)
	if err != nil || t.IsZero() {
		return nil, err
	}
	return &t, nil
}

// ArchiveAndClear copies all current repositories to repositories_archive, then deletes them.
// Call before each fetch to get a fresh list with no leftover from previous runs.
func (s *Store) ArchiveAndClear() (int64, error) {
	// Ensure archive table exists (for local dev without migrations)
	_, _ = s.db.Exec(`
		CREATE TABLE IF NOT EXISTS repositories_archive (
			id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			archived_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
			github_id BIGINT NOT NULL,
			owner TEXT NOT NULL,
			name TEXT NOT NULL,
			description TEXT,
			language TEXT,
			stars INTEGER,
			forks INTEGER,
			issues INTEGER,
			score FLOAT DEFAULT 0,
			created_at TIMESTAMPTZ,
			updated_at TIMESTAMPTZ,
			last_scanned_at TIMESTAMPTZ,
			owner_followers INTEGER DEFAULT 0,
			owner_repo_count INTEGER DEFAULT 0,
			velocity_badge TEXT
		)
	`)

	// Copy current repos to archive
	result, err := s.db.Exec(`
		INSERT INTO repositories_archive (
			archived_at, github_id, owner, name, description, language,
			stars, forks, issues, score, created_at, updated_at, last_scanned_at,
			owner_followers, owner_repo_count, velocity_badge
		)
		SELECT NOW(), github_id, owner, name, description, language,
			stars, forks, issues, score, created_at, updated_at, last_scanned_at,
			COALESCE(owner_followers, 0), COALESCE(owner_repo_count, 0), velocity_badge
		FROM repositories
	`)
	if err != nil {
		return 0, fmt.Errorf("failed to archive repos: %w", err)
	}
	archived, _ := result.RowsAffected()

	// Delete metrics_history (FK from repos)
	_, err = s.db.Exec(`DELETE FROM metrics_history`)
	if err != nil {
		return 0, fmt.Errorf("failed to clear metrics_history: %w", err)
	}

	// Delete all repos
	_, err = s.db.Exec(`DELETE FROM repositories`)
	if err != nil {
		return 0, fmt.Errorf("failed to clear repositories: %w", err)
	}

	return archived, nil
}

// PruneOldArchives deletes archive rows older than `days` days.
func (s *Store) PruneOldArchives(days int) (int64, error) {
	result, err := s.db.Exec(`
		DELETE FROM repositories_archive
		WHERE archived_at < NOW() - make_interval(days => $1)
	`, days)
	if err != nil {
		return 0, fmt.Errorf("failed to prune archives: %w", err)
	}
	n, _ := result.RowsAffected()
	return n, nil
}
