package storage

import (
	"database/sql"
	"fmt"

	"github.com/babacar/gemhunter/internal/models"
	_ "github.com/jackc/pgx/v5/stdlib"
)

type Store struct {
	db *sql.DB
}

func NewStore(connString string) (*Store, error) {
	db, err := sql.Open("pgx", connString)
	if err != nil {
		return nil, fmt.Errorf("failed to open database: %w", err)
	}
	if err := db.Ping(); err != nil {
		return nil, fmt.Errorf("failed to ping database: %w", err)
	}
	return &Store{db: db}, nil
}

func (s *Store) Init() error {
	query := `
	CREATE TABLE IF NOT EXISTS repositories (
		id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
		github_id BIGINT UNIQUE NOT NULL,
		owner TEXT NOT NULL,
		name TEXT NOT NULL,
		description TEXT,
		language TEXT,
		stars INTEGER,
		forks INTEGER,
		issues INTEGER,
		score FLOAT DEFAULT 0,
		created_at TIMESTAMPTZ,
		updated_at TIMESTAMPTZ,
		last_scanned_at TIMESTAMPTZ
	);
	CREATE TABLE IF NOT EXISTS metrics_history (
		id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
		repo_id BIGINT REFERENCES repositories(id),
		captured_at TIMESTAMPTZ DEFAULT NOW(),
		stars INTEGER,
		forks INTEGER
	);
	CREATE INDEX IF NOT EXISTS idx_repositories_score ON repositories(score DESC);
	`
	_, err := s.db.Exec(query)
	if err != nil {
		return fmt.Errorf("failed to init schema: %w", err)
	}
	return nil
}

func (s *Store) SaveRepo(r *models.Repository) error {
	query := `
	INSERT INTO repositories (github_id, owner, name, description, language, stars, forks, issues, score, created_at, updated_at, last_scanned_at, owner_followers, owner_repo_count, velocity_badge)
	VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15)
	ON CONFLICT(github_id) DO UPDATE SET
		stars = excluded.stars,
		forks = excluded.forks,
		issues = excluded.issues,
		score = excluded.score,
		updated_at = excluded.updated_at,
		last_scanned_at = excluded.last_scanned_at,
		owner_followers = excluded.owner_followers,
		owner_repo_count = excluded.owner_repo_count,
		velocity_badge = excluded.velocity_badge
	RETURNING id;
	`
	var repoID int64
	err := s.db.QueryRow(query, 
		r.GithubID, r.Owner, r.Name, r.Description, r.Language, 
		r.Stars, r.Forks, r.Issues, r.Score, r.CreatedAt, r.UpdatedAt, r.LastScannedAt,
		r.OwnerFollowers, r.OwnerRepoCount, r.VelocityBadge,
	).Scan(&repoID)
	
	if err != nil {
		return fmt.Errorf("failed to save repo: %w", err)
	}

	r.ID = repoID

	_, err = s.db.Exec(`INSERT INTO metrics_history (repo_id, stars, forks) VALUES ($1, $2, $3)`, repoID, r.Stars, r.Forks)
	return err
}

func (s *Store) ListRepos() ([]models.Repository, error) {
	rows, err := s.db.Query(`SELECT id, github_id, owner, name, description, language, stars, forks, issues, created_at, updated_at, last_scanned_at FROM repositories ORDER BY stars DESC LIMIT 100`)
	if err != nil {
		return nil, fmt.Errorf("query failed: %w", err)
	}
	defer rows.Close()

	var repos []models.Repository
	for rows.Next() {
		var r models.Repository
		if err := rows.Scan(
			&r.ID, &r.GithubID, &r.Owner, &r.Name, &r.Description, &r.Language,
			&r.Stars, &r.Forks, &r.Issues, &r.CreatedAt, &r.UpdatedAt, &r.LastScannedAt,
		); err != nil {
			return nil, err
		}
		repos = append(repos, r)
	}
	return repos, nil
}

func (s *Store) Close() error {
	return s.db.Close()
}
